### ISSUE TITLE
[1.20.1] Circuit Slicer does not accept automatic fluid inputs

### ISSUE THREAD

**Issue by AlphaFromOmega** [GlodBlock/ExtendedAE#309]
The circuit slicer does not accept fluid inputs pumped in from sources such as export buses or pattern providers. This also extends to fluid handling from other mods, such as Mekanism's pipes or Integrated Tunnels I/O, not outputting fluid to the slicer.

**Comment by GlodBlock** [comment]
fixed

**Comment by AlphaFromOmega** [comment]
Still not working after the update
![2024-12-24_13 56 40](https://github.com/user-attachments/assets/08747024-3798-4483-b637-2b870f78b318)
Mekanism pipes do not connect, and the eternal water source does not output to it
![2024-12-24_13 50 34](https://github.com/user-attachments/assets/d93a4878-17eb-4560-9533-e28847c4c421)
Exporting items to it works fine but exporting water to the slicer does not work still
![2024-12-24_13 52 38](https://github.com/user-attachments/assets/578af2cf-6479-42a7-9bdf-32edf19c949e)
![2024-12-24_13 52 41](https://github.com/user-attachments/assets/11c47b30-32cb-4009-a0b1-dfff14c3dd5f)

**Comment by GlodBlock** [comment]
it works on my machine, with mek pipe

https://github.com/user-attachments/assets/50c48437-afd6-4ebd-b301-d89443074eb3

**Comment by akanealw** [comment]
I had the same issue even after the fix. Did a clean instance with just AE2 and ExtendedAE and I was able to push recipes to the slicer successfully. I then installed all the ae2 addons I normally have and it stopped working. On a hunch, I removed AECapFix and the slicer started working again.
